name: cd_prd

on:
  push:
    branches:
      - master

env:
  NODE_ENV: production

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0

      # Build docker image
      - name: Build Docker Image
        run: |-
          docker build -t us.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }} .
      # Configure docker to use the gcloud command-line tool as a credential helper
      - run: |
          gcloud auth configure-docker -q
      # Push image to Google Container Registry
      - name: Push Docker Image to GCR
        run: |-
          docker push us.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy Image to Cloud Run
    runs-on: ${{ matrix.os }}
    needs: build
    environment: Production

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF##*/})" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: us.gcr.io/${{ secrets.PROJECT_ID }}/${{ secrets.SERVICE_NAME }}:${{ github.sha }}
          service: ${{ secrets.SERVICE_NAME }}-${{ env.BRANCH_NAME }}
          region: ${{ secrets.SERVICE_REGION }}